# This docker-compose.yml is for demonstration purposes. If you run
# docker-compose build && docker-compose up, you will have a local mosquitto
# mqtt server running and a ticker microservice, which is using the
# microservice-adapter-mqtt connected to it, publishing a tick message every
# 3 seconds with topic default/tick. You can e.g. use mqtt-spy to monitor these
# messages.
version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
    networks:
      - service-network
    volumes:
      - "./examples/conf.d/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    restart: always
  microservice-adapter-mqtt:
    depends_on:
      - mqtt
    build: .
    image: flaneurtv/microservice-adapter-mqtt
    environment:
      - "LOG_LEVEL=debug"
      - "LOG_LEVEL_MQTT=debug"
      - "NAMESPACE_LISTENER=default"
#      - "MQTT_LISTENER_URL=tcp://mqtt:1883"
      - "NAMESPACE_PUBLISHER=default"
#      - "MQTT_PUBLISHER_URL=tcp://mqtt:1883"
    networks:
      - service-network
    restart: always
    volumes:
      - ./examples/test-echo/:/srv/
  test-sender:
    depends_on:
      - microservice-adapter-mqtt
      - mqtt
    build: ./examples/test-sender
    image: flaneurtv/microservice-test-sender
    environment:
#      - "SUBSCRIPTIONS="
      - "LOG_LEVEL=debug"
      - "LOG_LEVEL_MQTT=debug"
      - "NAMESPACE_LISTENER=default"
#      - "MQTT_LISTENER_URL=tcp://mqtt:1883"
      - "NAMESPACE_PUBLISHER=default"
#      - "MQTT_PUBLISHER_URL=tcp://mqtt:1883"
    networks:
      - service-network
    volumes:
#      - ./examples/test-sender/:/srv/
#      - ./examples/test-sender/subscriptions-1-line-empty.txt:/srv/subscriptions.txt
      - ./examples/test-sender/subscriptions-2-lines-empty.txt:/srv/subscriptions.txt
#      - ./examples/test-sender/subscriptions-bogus.txt:/srv/subscriptions.txt
    restart: always
networks:
  service-network:
