# This docker-compose.yml is for demonstration purposes. If you run
# docker-compose build && docker-compose up, you will have a local mosquitto
# mqtt server running and a ticker microservice, which is using the
# microservice-adapter-mqtt connected to it, publishing a tick message every
# 3 seconds with topic default/tick. You can e.g. use mqtt-spy to monitor these
# messages.
version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
    networks:
      - service-network
    volumes:
      - "./examples/conf.d/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    restart: always
  microservice-adapter-mqtt:
    build: .
    image: flaneurtv/microservice-adapter-mqtt
  test-sender:
    build: ./examples/test-sender
    image: flaneurtv/microservice-test-sender
    environment:
      - "LOG_LEVEL=debug"
      - "NAMESPACE_LISTENER=default"
      - "MQTT_LISTENER_URL=tcp://mqtt:1883"
      - "NAMESPACE_PUBLISHER=default"
      - "MQTT_PUBLISHER_URL=tcp://mqtt:1883"
    networks:
      - service-network
    volumes:
      - ./examples/test-sender/:/srv/test-sender/
    restart: always
  test-echo:
    build: ./examples/test-echo
    image: flaneurtv/microservice-test-echo
    environment:
      - "LOG_LEVEL=debug"
      - "NAMESPACE_LISTENER=default"
      - "MQTT_LISTENER_URL=tcp://mqtt:1883"
      - "NAMESPACE_PUBLISHER=default"
      - "MQTT_PUBLISHER_URL=tcp://mqtt:1883"
    networks:
      - service-network
    volumes:
      - ./examples/test-echo/:/srv/test-echo/
    restart: always
networks:
  service-network:
