# This docker-compose.yml is for demonstration purposes. If you run 
# docker-compose build && docker-compose up, you will have a local mosquitto 
# mqtt server running and a ticker microservice, which is using the 
# microservice-adapter-mqtt connected to it, publishing a tick message every 
# 3 seconds with topic default/tick. You can e.g. use mqtt-spy to monitor these 
# messages.
version: '3'
services:
  microservice-adapter-mqtt:
    build: .
    image: flaneurtv/microservice-adapter-mqtt
  ticker:
    depends_on: 
      - microservice-adapter-mqtt
      - mqtt
    build: ./examples/ticker
    image: flaneurtv/microservice-ticker
    environment:
      - "DEBUG=true"
      - "NAMESPACE_LISTENER=default"
      - "MQTT_LISTENER_URL=tcp://mqtt:1883"
#      - "MQTT_LISTENER_URL=tcp://iot.eclipse.org:1883"
#      - "MQTT_LISTENER_URL=tcp://m20.cloudmqtt.com:13701"
      - "NAMESPACE_PUBLISHER=flaneur"
      - "MQTT_PUBLISHER_URL=tcp://mqtt:1883"
#      - "MQTT_PUBLISHER_URL=tcp://m20.cloudmqtt.com:13701"
#      - "MQTT_PUBLISHER_URL=tcp://iot.eclipse.org:1883"
    volumes:
       - ./examples/ticker/schema-tick-hugestring.json:/srv/ticker/schema-tick.json
#      - ./local/mqtt_listener.json:/run/secrets/mqtt_listener.json
#      - ./local/mqtt_publisher.json:/run/secrets/mqtt_publisher.json
    networks:
      - service-network
  tick-responder:
    depends_on: 
      - microservice-adapter-mqtt
      - mqtt
    build: ./examples/tick-responder
    image: flaneurtv/microservice-tick-responder
    environment:
      - "DEBUG=true"
      - "NAMESPACE_LISTENER=flaneur"
      - "MQTT_LISTENER_URL=tcp://mqtt:1883"
#      - "MQTT_LISTENER_URL=tcp://iot.eclipse.org:1883"
#      - "MQTT_LISTENER_URL=tcp://m20.cloudmqtt.com:13701"
      - "NAMESPACE_PUBLISHER=test"
      - "MQTT_PUBLISHER_URL=tcp://mqtt:1883"
#      - "MQTT_PUBLISHER_URL=tcp://m20.cloudmqtt.com:13701"
#      - "MQTT_PUBLISHER_URL=tcp://iot.eclipse.org:1883"
#    volumes:
#      - ./local/mqtt_listener.json:/run/secrets/mqtt_listener.json
#      - ./local/mqtt_publisher.json:/run/secrets/mqtt_publisher.json
    networks:
      - service-network
  mqtt:
    image: eclipse-mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
    networks:
      - service-network
    volumes:
      - "./examples/conf.d/mosquitto.conf:/mosquitto/config/mosquitto.conf"
  mqtt2:
    image: eclipse-mosquitto
    ports:
     - "1884:1883"
     - "9002:9001"
    networks:
      - service-network
    volumes:
      - "./examples/conf.d/mosquitto.conf:/mosquitto/config/mosquitto.conf"
  bridge-tick:
    depends_on: 
      - microservice-adapter-mqtt
      - mqtt
      - mqtt2
    build: ./examples/bridge-tick
    image: flaneurtv/microservice-bridge-tick
    environment:
      - "DEBUG=true"
      - "NAMESPACE_LISTENER=flaneur"
      - "NAMESPACE_PUBLISHER=bridged"
      - "MQTT_LISTENER_URL=tcp://mqtt:1883"
#      - "MQTT_LISTENER_URL=tcp://iot.eclipse.org:1883"
#      - "MQTT_LISTENER_URL=tcp://m20.cloudmqtt.com:13701"
      - "MQTT_PUBLISHER_URL=tcp://mqtt2:1883"
#      - "MQTT_PUBLISHER_URL=tcp://m20.cloudmqtt.com:13701"
#      - "MQTT_PUBLISHER_URL=tcp://iot.eclipse.org:1883"
#    volumes:
#      - ./local/mqtt_listener.json:/run/secrets/mqtt_listener.json
#      - ./local/mqtt_publisher.json:/run/secrets/mqtt_publisher.json
    networks:
      - service-network
  bridge-tick-responder:
    depends_on: 
      - microservice-adapter-mqtt
      - mqtt
      - mqtt2
    build: ./examples/bridge-tick-responder
    image: flaneurtv/microservice-bridge-tick-responder
    environment:
      - "DEBUG=true"
      - "NAMESPACE_LISTENER=test"
      - "NAMESPACE_PUBLISHER=bridged"
      - "MQTT_LISTENER_URL=tcp://mqtt:1883"
#      - "MQTT_LISTENER_URL=tcp://iot.eclipse.org:1883"
#      - "MQTT_LISTENER_URL=tcp://m20.cloudmqtt.com:13701"
      - "MQTT_PUBLISHER_URL=tcp://mqtt2:1883"
#      - "MQTT_PUBLISHER_URL=tcp://m20.cloudmqtt.com:13701"
#      - "MQTT_PUBLISHER_URL=tcp://iot.eclipse.org:1883"
#    volumes:
#      - ./local/mqtt_listener.json:/run/secrets/mqtt_listener.json
#      - ./local/mqtt_publisher.json:/run/secrets/mqtt_publisher.json
    networks:
      - service-network
networks:
  service-network:
